//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopVideoRecorder.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopVideoRecorder.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpeg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FFmpeg_Category {
            get {
                return ResourceManager.GetString("FFmpeg_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay time after starting ffmpeg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_DelayAfter_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_DelayAfter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DelayAfter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_DelayAfter_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_DelayAfter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scope for desktop recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set true, disabled this activity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_DisableActivity_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_DisableActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisableActivity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_DisableActivity_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_DisableActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RecordDesktopVideoScope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_ExtraOptionString_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_ExtraOptionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExtraOptionString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_ExtraOptionString_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_ExtraOptionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full path to ffmpeg.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_FFmpegFilePath_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_FFmpegFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpegFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_FFmpegFilePath_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_FFmpegFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame rate (fps) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_FrameRate_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_FrameRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FrameRate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_FrameRate_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_FrameRate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max duration (sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_MaxDuration_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_MaxDuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxDuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_MaxDuration_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_MaxDuration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max file size (Mbyte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_MaxFileSize_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_MaxFileSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxFileSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_MaxFileSize_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_MaxFileSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full path to output file.(fie name should be end with .avi, .mp4 etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_OutputFileName_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_OutputFileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OutputFileName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_OutputFileName_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_OutputFileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PixelFormat. Default is yuv420p に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_PixelFormat_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_PixelFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PixelFormat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_PixelFormat_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_PixelFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video codec. Default is libx264. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_VideoCodec_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_VideoCodec_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VideoCodec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_VideoCodec_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_VideoCodec_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video size string (eg. &quot;1920x1024&quot;) If not set, desktop size is automatically applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_VideoSize_Description {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_VideoSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VideoSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecordDesktopVideoScope_VideoSize_DisplayName {
            get {
                return ResourceManager.GetString("RecordDesktopVideoScope_VideoSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay time after starting ffmpeg.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_DelayAfter_Description {
            get {
                return ResourceManager.GetString("StartRecording_DelayAfter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DelayAfter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_DelayAfter_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_DelayAfter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartRecording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_Description {
            get {
                return ResourceManager.GetString("StartRecording_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag if this activity is disable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_DisableActivity_Description {
            get {
                return ResourceManager.GetString("StartRecording_DisableActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisableActivity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_DisableActivity_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_DisableActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartRecording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra String Option (eg. Cropping : &quot;-vf  crop=100:80:320:240&quot; ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_ExtraOptionString_Description {
            get {
                return ResourceManager.GetString("StartRecording_ExtraOptionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExtraOptionString に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_ExtraOptionString_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_ExtraOptionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full path to ffmpeg.exe. This string should be ended with ffmpeg.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_FFmpegFilePath_Description {
            get {
                return ResourceManager.GetString("StartRecording_FFmpegFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpegFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_FFmpegFilePath_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_FFmpegFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use this process in StopRecording activity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_FFmpegProcess_Description {
            get {
                return ResourceManager.GetString("StartRecording_FFmpegProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpegProcess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_FFmpegProcess_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_FFmpegProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FrameRate(fps) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_FrameRate_Description {
            get {
                return ResourceManager.GetString("StartRecording_FrameRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FrameRate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_FrameRate_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_FrameRate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxDuration(sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_MaxDuration_Description {
            get {
                return ResourceManager.GetString("StartRecording_MaxDuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxDuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_MaxDuration_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_MaxDuration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max file size (MByte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_MaxFileSize_Description {
            get {
                return ResourceManager.GetString("StartRecording_MaxFileSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxFileSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_MaxFileSize_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_MaxFileSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output video filename. This string should be ended with .avi .mp4 etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_OutputFileName_Description {
            get {
                return ResourceManager.GetString("StartRecording_OutputFileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OutputFileName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_OutputFileName_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_OutputFileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PixelFormat. Default is yuv420p に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_PixelFormat_Description {
            get {
                return ResourceManager.GetString("StartRecording_PixelFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PixelFormat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_PixelFormat_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_PixelFormat_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VideoCodec. Default is libx264 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_VideoCodec_Description {
            get {
                return ResourceManager.GetString("StartRecording_VideoCodec_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VideoCodec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_VideoCodec_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_VideoCodec_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VideoSize String (eg 1920x180) If not set, desktop size is automatically applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_VideoSize_Description {
            get {
                return ResourceManager.GetString("StartRecording_VideoSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VideoSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartRecording_VideoSize_DisplayName {
            get {
                return ResourceManager.GetString("StartRecording_VideoSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopRecording_Description {
            get {
                return ResourceManager.GetString("StopRecording_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StopRecording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopRecording_DisplayName {
            get {
                return ResourceManager.GetString("StopRecording_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process to stop. Usunally, this is from StartRecording activity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopRecording_FFmpegProcess_Description {
            get {
                return ResourceManager.GetString("StopRecording_FFmpegProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpegProcess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopRecording_FFmpegProcess_DisplayName {
            get {
                return ResourceManager.GetString("StopRecording_FFmpegProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
